### ISSUE TITLE
Pytorch version to build the model

### ISSUE THREAD

**Issue by BurakaKrishna** [Tina-19/Question-Generation#1]
Hi Tina, i have tried replicating the same model using Pytorch 0.4.1, but when training the model i am getting
**RuntimeError**: _The size of tensor a (1344) must match the size of tensor b (64) at non-singleton dimension 1 in the loss.py_
Can you help me guide how to fix it ?

**Comment by vamsibanda** [comment]
@BurakaKrishna Do you able to fix the problem? if you did; can you tell me how you did it?

**Comment by lpzt** [comment]
I reported an error while running the embedding.py file, can you help me solve it？
`D:\bishe\QG\Question-Generation-master>python embedding.py  -embedding  data/processed/tgt-train.txt -dict data/data.tgt.dict  -output data/tgt.840B.
300d
Unknown word: <blank>
Unknown word: <unk>
Unknown word: <s>
Unknown word: </s>
Traceback (most recent call last):
  File "embedding.py", line 55, in <module>
    main()
  File "embedding.py", line 42, in main
    embedding[i] = word2embedding[w]
TypeError: float() argument must be a string or a number, not 'map'
D:\bishe\QG\Question-Generation-master>python embedding.py  -embedding  data/processed/tgt-train.txt -dict data/data.tgt.dict  -output data/tgt.840B.
300d
Traceback (most recent call last):
  File "embedding.py", line 55, in <module>
    main()
  File "embedding.py", line 29, in main
    word2embedding[line[0]] = np.asarray(list(map(float, line[1 : ])))
ValueError: could not convert string to float: 'you'
`
